### ISSUE TITLE
Unable to set serial port parameters with VISAAdapter

### ISSUE THREAD

**Issue by msmttchr** [pymeasure/pymeasure#412]
Hi,

I have just found anissue related to use of VISAAdapter with an instrument connected via RS232. See log below:
```
>>> from pymeasure.instruments.hp import hp34401A
>>> i=hp34401A.HP34401A('ASRL5::INSTR', baud_rate=9600, data_bits=7, parity=2)
>>> i.adapter.connection.data_bits
8
>>> i.adapter.connection.parity
<Parity.none: 0>
>>> i.id
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\michele sardo\AppData\Local\Programs\Python\Python39\lib\site-packages\pymeasure\instruments\instrument.py", line 81, in id
    return self.adapter.ask("*IDN?").strip()
  File "C:\Users\michele sardo\AppData\Local\Programs\Python\Python39\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\michele sardo\AppData\Local\Programs\Python\Python39\lib\site-packages\pyvisa\resources\messagebased.py", line 644, in query
    return self.read()
  File "C:\Users\michele sardo\AppData\Local\Programs\Python\Python39\lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1: ordinal not in range(128)
>>> i.adapter.connection.data_bits=7
>>> i.adapter.connection.parity=2
>>> i.id
'HEWLETT-PACKARD,34401A,0,11-5-3'
```

The instrument is expecting `baud_rate=9600`, `data_bits=7` and `parity=2` (even)., but as You can see from the log above, the parameters are not passed to pyvisa `open_resource` call, because they are filter by `safeKeywords `list. Indeed also `baud_rate` is not passed, but the default happens to be 9600.

I think this `safeKeyword ` filtering is some legacy code whose purpose is not clear to me and it should be update or removed.

**Comment by bilderbuchi** [comment]
This is #334, I'll close this as a duplicate.
The purpose is to retain the generic nature of our Adapters. Unfortunately, in the case of PyVISA, you don't know which set of kwargs is "safe" before creating the resource (due to PyVISA's dynamic handling of that).
