### ISSUE TITLE
Fix Parker GV6 instrument implementation

### ISSUE THREAD

**Issue by bilderbuchi** [pymeasure/pymeasure#623]
### Discussed in https://github.com/pymeasure/pymeasure/discussions/620

<div type='discussions-op-text'>

<sup>Originally posted by **flynnd3** May  4, 2022</sup>
I'm sorry for asking this here as it's probably not the place for it, but can someone give me some example code to connect to a parker drive as I'm having no luck.
I'm new to programming and would place myself in the low end of the intermediate level, but have a need to connect to a Parker GV6 drive.
running python 3.9 on Windows 10 and have had trouble with this.

I have tried multiple variations to get a connection to the drive, and the one that got the furthest with the following:

`from pymeasure.instruments.parker import Parker.GV6 as drive`
`test = drive("COM2")`

after that last command, I get the following.

`Traceback (most recent call last):`
 `File "<stdin>", line 1, in <module>`
 `File "C:\Users\flynnd3\AppData\Roaming\Python\Python39\site-packages\pymeasure\instruments\parker\parkerGV6.py", line 40, in __init__`
  `  super(ParkerGV6, self).__init__(`
 `File "C:\Users\flynnd3\AppData\Roaming\Python\Python39\site-packages\pymeasure\instruments\instrument.py", line 69, in __init__`
  `  self.status = self.measurement("*STB?",`
`AttributeError: can't set attribute`

Any help greatly appreciated on this</div>

It turns out that this instrument is very old and its implementation currently nonfunctional.

Necessary fixes identified so far: 
* Use correct method name `set_defaults()` throughout
* `echo` is a method, not a property, so call it instead: ` self.echo(False)`
* In the overridden `write()`, call `super().write(...)`.
* Actually, don't use that way of prescribing the line ending, but use our current method with init arguments.
* The custom `read()` method also seems to be buggy, as [pointed out ](https://github.com/pymeasure/pymeasure/discussions/620#discussioncomment-2732260) by @msmttchr. It seems this instrument creates a command prompt of sorts that we need to strip out.

**Comment by bilderbuchi** [comment]
Better [connection configuration ](https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments.html#defining-default-connection-settings)(needs to be tested with hardware)
I see no reason to force use of `SerialAdapter` here, so let's use the preferred VISAAdapter approach:

```
    def __init__(self, port, **kwargs):
        kwargs.setdefault('timeout', 500)
        kwargs.setdefault('baud_rate', 9600)
        kwargs.setdefault('write_termination', '\r')
        super().__init__(
            port,
            "Parker GV6 Motor Controller",
            **kwargs,
        )
        self.set_defaults()
```
and remove the custom `write()` method completely.
